[package]
name = "garden"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
glob = "0.3.1"
serde = { workspace = true }
serde_json = { workspace = true }
yardbird = { path = ".." }
